export const apiLogin = 'http://localhost:5050/api/login'
export const apiLogout = 'http://localhost:5050/api/logout'

export const apiProductLine =  'http://localhost:5050/api/productlines'
export const apiOffice = 'http://localhost:5050/api/admin/offices'
// export const apiOffice =  'https://637cfc2a16c1b892ebc4d885.mockapi.io/api/employees'
export const apiProduct = 'http://localhost:5050//api/products'
export const apiCustomer = 'http://localhost:5050/api/customers'
export const apiGetWarranty = 'http://localhost:5050/api/list_warranty'
export const apiGetAgent = 'http://localhost:5050/api/list_agent'
export const apiLots = 'http://localhost:5050/api/lots'